# Generated by Django 5.2.10 on 2026-01-08 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_category_id_alter_pricerecord_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricerecord",
            name="date_recorded",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата записи"
            ),
        ),
    ]
